# Generated by Django 4.2.7 on 2024-12-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BTCto1M", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="btcpost",
            name="btc_price",
            field=models.IntegerField(),
        ),
    ]
