# Generated by Django 4.2.7 on 2024-12-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BTCto1M", "0003_rename_link_btcpost_image_link_btcpost_tweet_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="btcpost",
            name="btc_price",
            field=models.FloatField(),
        ),
    ]
